#Navnet på dette workflow
name: .NET Core Desktop

#Events i dette workflow, de kører kun ved push. 
on:
  push:
    branches: [ master ]
#Jobs der er i dette event 
jobs:
  build:
  #kører på en github hoasted windows maskine 
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Install dependencies
      run: dotnet restore   
      
    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal
      
